.TH S9S 1 "August 29, 2016"

.SH NAME
s9s-backup \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-cluster
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B \-L, \-\-list
List the backups known for the controller.

.TP
.B \-\-create
Create a new backup.

.SS Generic Options

.TP
.B \-\-help
Print the help message and exist.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " [\fIPROT\fP://]\fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" [\fIPROT\fP://]\\fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The protocol and port is also accepted as
part of the hostname (e.g. --controller="https://127.0.0.1:9556").

.TP
.B \-h, \-\-human-readable
Print the sizes of files in human readable format.

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.

.TP
.B \-l, \-\-long
This option is similar to the -l option for the standard ls UNIX utility
program. If the program creates a list of objects this option will change its
format to show more details.

.TP
.B \-\-print-json
The JSON strings will be printed while communicating with the controller. This 
option is for debugging purposes.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.\"
.\"
.\"
.SS Job Related Options

.TP
.B \-\-wait
If the application created a job (e.g. to create a new cluster) and this command
line option is provided it will wait until the job is executed. While waiting a
progress bar will be shown unless the silent mode is set.

.TP
.B \-\-log
If the application created a job (e.g. to create a new cluster) and this command
line option is provided it will wait until the job is executed. While waiting
the job logs will be shown unless the silent mode is set.

.\"
.\"
.\"
.SS Cluster Related Options

.TP
.BI \-i " INTEGER" "\fR,\fP \-\^\-cluster-id=" INTEGER
If the operation related to an existing cluster this option can be used to
control which cluster will be manipulated. If the operation creates a new
cluster the cluster ID is assigned automatically, so this option can't be used.

.TP
.BI \-n " NAME" "\fR,\fP \-\^\-cluster-name=" NAME
Sets the cluster name. If the operation creates a new cluster this will be the
name of the new cluster. (Usage of this option for selecting an existing cluster
is not yet implemented.)

.TP
.BI \-\^\-nodes= NODELIST
The list of nodes or hosts enumerated in a special string using a semicolon as
field separator (e.g. "192.168.1.1;192.168.1.2"). 
The strings in the node list are urls that can have the following protocols:

.\"
.\"
.\"
.SS Backup Related Options

.TP
.BI \-\^\-backup\-method= METHOD
Controls what backup software is going to be used to create the backup. The
Cmon controller currently supports the following methods: ndb, mysqldump, 
xtrabackupfull, xtrabackupincr, mongodump, pg_dump, mysqlpump.

.TP
.BI \-\^\-backup\-directory= DIR
Sets where the created archive files are going to be placed.

.TP
.BI \-\^\-no\-compression
Do not compress the archive file created by the backup.

.TP
.BI \-\^\-use\-pigz
Use the pigz program to compress archive.

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
Here is an example showing how to create a new cluster:

.nf
# \fBs9s backup --create --nodes=192.168.1.199 --cluster-id=1 --wait\fR
.fi

Another example simply lists the backup files:

.nf
# \fBs9s backup --list --cluster-id=1 --long -h\fR
.fi

