.TH S9S-NODE 1 "October 4, 2017"

.SH NAME
s9s-node \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-node
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:
