.TH S9S-CONTROLLER 1 "March 21, 2019"

.SH NAME
s9s-controller \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-container
.RI [OPTION]... 

.SH DESCRIPTION

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:


