.TH S9S-NODE 1 "August 29, 2016"

.SH NAME
s9s-node \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-cluster
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B \-L, \-\-list
List the nodes managed by the controller.

.TP
.B \-\-stat
Print the details of one or more nodes.

.TP
.B \-\-set
Sets various properties of the specified node/host.

.TP
.B \-\-list\-config
List the configuration values for the given node.

.TP
.B \-\-set\-config
Change configuration values for the given node.

.TP
.B \-\-pull\-config
Copy the configuration file(s) from the node to the local computer. Use the 
\fB\-\-output\-dir\fP to control where the files will be created.

.SS Generic Options

.TP
.B \-\-help
Print the help message and exist.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " [\fIPROT\fP://]\fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" [\fIPROT\fP://]\\fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The protocol and port is also accepted as
part of the hostname (e.g. --controller="https://127.0.0.1:9556").

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.BI \-u " USERNAME" "\fR,\fP \-\^\-cmon\-user=" USERNAME
The name of the user that is going to be used to authenticate on the Cmon
Controller. This can also be set as the \fBcmon_user\fP configuration file 
value, but the command line option of course has precedence over the
configuration file. 

.TP
.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.

.TP
.B \-l, \-\-long
This option is similar to the -l option for the standard ls UNIX utility
program. If the program creates a list of objects this option will change its
format to show more details.

.TP 
.BI \-\-opt\-group= GROUP
Configuration option group that is usually written as "[GROUP]" in the
configuration files.

.TP
.BI \-\-opt\-name= NAME
Configuration option name.

.TP 
.BI \-\-opt\-value= VALUE
Configuration option value.

.TP
.B \-\-print-json
The JSON strings will be printed while communicating with the controller. This 
option is for debugging purposes.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.\"
.\"
.\"
.SS Node Related Options

.TP
.BI \-\^\-properties= ASSIGNMENT
One or more assignments specifying property names and values. The assignment
operator is the '=' character (e.g. --properties='alias="newname"'), multiple
assignments are separated by the semicolon (';').

.TP
.BI \-\^\-output\-dir= DIRECTORY
The directory where the output files will be created on the local computer.

.\"
.\"
.\"
.SS Cluster Related Options

.TP
.BI \-i " INTEGER" "\fR,\fP \-\^\-cluster-id=" INTEGER
Controls which cluster to check.

.TP
.BI \-n " NAME" "\fR,\fP \-\^\-cluster-name=" NAME
Controls which cluster to check.

.TP
.BI \-\^\-nodes= NODELIST
The list of nodes or hosts enumerated in a special string using a semicolon as
field separator (e.g. "192.168.1.1;192.168.1.2"). 
The strings in the node list are urls that can have the following protocols:

.\" 
.\" Here is how we make a 7 character deep left indent from the .RS to the .RE
.\" formatters. This is by the way the list of the supported protocols.
.\" 
.RS 7
.TP
.B mysql:// 
The protocol for MySql servers. Use this string to specify MySql servers.
.TP
.B ndbd://
Someone has to write this part.
.TP
.B ndb_mgmd://
Someone has to write this part. The mgmd:// notation is also accepted.
.RE

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
List the nodes managed by the controller:

.nf
# \fBs9s node --list --long --controller=https://localhost:9556 --color=always\fR
.fi

List a few specific nodes from one specific cluster:

.nf
# \fBs9s node --list --long --cluster-name=ft_postgresql_36945 '*168.0*' '10.10*'\fR
.fi

Change a configuration value for a PostgreSQL server:

.nf
# \fBs9s node --change-config --nodes=192.168.1.115 --opt-name=log_line_prefix --opt-value='%m '\fR
.fi

Change the "alias" property for a host, giving it a "nickname" to be used in
lists and command line options:

.nf
# \fBs9s node --set --nodes=192.168.1.127 --properties="alias=controller"\fR
.fi
