.TH S9S-NODE 1 "August 29, 2016"

.SH NAME
s9s-node \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-node
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B \-L, \-\-list
List the nodes managed by the controller.

.TP
.B
\-\-restart
Restart the node. This means the process that provides the main functionality on
the node (e.g. the MySql daemon on a Galera node) will be stopped then start
again.

.TP
.B \-\-start
Start the node. This means the process that provides the main functionality on
the node (e.g. the MySql daemon on a Galera node) will be start.

.TP
.B \-\-stop
Stop the node. This means the process that provides the main functionality on
the node (e.g. the MySql daemon on a Galera node) will be stopped.

.TP
.B \-\-stat
Print the details of one or more nodes.

.TP
.B \-\-set
Sets various properties of the specified node/host.

.TP
.B \-\-list\-config
List the configuration values for the given node.

.TP
.B \-\-set\-config
Change configuration values for the given node.

.TP
.B \-\-pull\-config
Copy the configuration file(s) from the node to the local computer. Use the 
\fB\-\-output\-dir\fP to control where the files will be created.

.SS Generic Options

.TP
.B \-\-help
Print the help message and exist.

.TP
.B \-\-debug
Print even the debug level messages.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " [\fIPROT\fP://]\fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" [\fIPROT\fP://]\\fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The protocol and port is also accepted as
part of the hostname (e.g. --controller="https://127.0.0.1:9556").

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.BI \-u " USERNAME" "\fR,\fP \-\^\-cmon\-user=" USERNAME
The name of the user that is going to be used to authenticate on the Cmon
Controller. This can also be set as the \fBcmon_user\fP configuration file 
value, but the command line option of course has precedence over the
configuration file. 

.TP
.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.

.TP
.B \-l, \-\-long
This option is similar to the -l option for the standard ls UNIX utility
program. If the program creates a list of objects this option will change its
format to show more details.

.TP 
.BI \-\-opt\-group= GROUP
Configuration option group that is usually written as "[GROUP]" in the
configuration files.

.TP
.BI \-\-opt\-name= NAME
Configuration option name.

.TP 
.BI \-\-opt\-value= VALUE
Configuration option value.

.TP
.B \-\-print-json
The JSON strings will be printed while communicating with the controller. This 
option is for debugging purposes.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.TP
.B \-\-force
Force the execution of potentially dangerous operations like restarting a
read-write node in a MySQL Replication cluster.

.\"
.\"
.\"
.SS Node Related Options

.TP
.BI \-\^\-properties= ASSIGNMENT
One or more assignments specifying property names and values. The assignment
operator is the '=' character (e.g. --properties='alias="newname"'), multiple
assignments are separated by the semicolon (';').

.TP
.BI \-\^\-output\-dir= DIRECTORY
The directory where the output files will be created on the local computer.

.\"
.\"
.\"
.SS Cluster Related Options

.TP
.BI \-i " INTEGER" "\fR,\fP \-\^\-cluster-id=" INTEGER
Controls which cluster to check.

.TP
.BI \-n " NAME" "\fR,\fP \-\^\-cluster-name=" NAME
Controls which cluster to check.

.TP
.BI \-\^\-nodes= NODELIST
The list of nodes or hosts enumerated in a special string using a semicolon as
field separator (e.g. "192.168.1.1;192.168.1.2").  The strings in the node list
are URLs (e.g.  "ndbd://192.168.1.1;ndb_mgmd://192.168.1.2"). The following
protocols are recognized with special meaning:

.\" 
.\" Here is how we make a 7 character deep left indent from the .RS to the .RE
.\" formatters. This is by the way the list of the supported protocols.
.\" 
.RS 7
.TP
.B mysql:// 
The protocol for MySql servers. Use this string to specify MySql servers.
.TP
.B ndbd://
Someone has to write this part.
.TP
.B ndb_mgmd://
Someone has to write this part. The mgmd:// notation is also accepted.
.TP
.B haproxy://
Used to create and manipulate HaProxy servers.
.TP
.B proxysql://
Use this to install and handle ProxySql servers.
.TP
.B maxscale://
The protocol to install and handle MaxScale servers.
.RE

.\"
.\"
.\"
.SH Graph options
.TP 
.BI \-\-graph= GRAPH_NAME
When providing a valid graph name together with the \fB--stat\fP option a graph
will be printed with statistical data. Currently the following graphs are
available:

.RS 7
.TP
.B cpughz
The graph will show the CPU clock frequency measured in GHz.
.TP
.B cpuload
Shows the average CPU load of the host computer.
.TP
.B cputemp
The temperature of the CPU measured in degree Celsius. Please note that to
measure the CPU temperature some kernel module might be needed (e.g. it might be
necessary to run \fBsudo modprobe coretemp\fP). On multiprocessor systems the
graph might show only the first processor.
.TP
.B memfree
The amount of the free memory measure in GBytes.
.TP
.B memutil
The memory utilization of the host measured in percent.
.TP
.B sqlcommands
Shows the number of SQL commands executed measured in 1/s.
.TP
.B sqlconnections
Shows the number of SQL connections.
.TP
.B swapfree
The size of the free swap space measured in GBytes.

.\"
.\"
.\"
.SH NODE LIST
Using the \fB\-\-list\fP and \fB\-\-long\fP command line options a detailed list
of the nodes can be printed. Here is an example of such a list:

.nf
# \fBs9s node --list --long '192.168.1.1*'\fP
STAT VERSION CID CLUSTER             HOST          PORT COMMENT
poM- 9.6.2     1 ft_postgresql_11794 192.168.1.117 8089 Up and running
coC- 1.4.2     1 ft_postgresql_11794 192.168.1.127 9555 Up and running
Total: 3

.fi

Please note that the list in the example is created using a filter (that
is '192.168.1.1*' in the example). The last line shows a 3 as total, the number
of nodes maintained by the controller, but only two of the nodes are printed in
the list because of the filter.

The list contains the following fields:
.RS 5
.TP
.B STAT
Some status information represented as individual letter. This field contains
the following characters:
.RS 5
.TP
.B nodetype
This is the type of the node. It can be \fBc\fP for controller, \fBg\fP for
Galera node, \fBx\fP for MaxScale node, \fBk\fP for Keepalived node, \fBp\fP for
PostgreSQL, \fBm\fP for Mongo, \fBe\fP for MemCached, \fBy\fP for ProxySql,
\fBh\fP for HaProxy, \fBa\fP for Garbd and \fBs\fP for generic MySQL nodes.
.TP
.B hoststatus
The status of the node. It can be \fBo\fP for on-line, \fBl\fP for off-line,
\fBf\fP for failed nodes, \fBr\fP for nodes performing recovery, \fB-\fP for
nodest that are shut down and \fB?\fP for nodes in unknown state.
.TP
.B role
This field shows the role of the node in the cluster. This can be \fBM\fP for
master, \fBS\fP for Slave, \fBU\fP for multi (master and slave), \fBC\fP for 
controller and \fB-\fP for everything else.
.TP 
.B maintenance
This field shows if the node is in maintenance mode. The character is \fbM\fP
for nodes in maintenance mode and \fB-\fP for nodes that are not in maintenance
mode.
.RE
.TP
.B VERSION
This field shows the version string of the software that provides the service
represented in the given line. Check for the documentation of the PORT field 
for more details.
.TP
.B CID
The cluster ID of the cluster that holds the node as a member. Every node
belongs to exactly one cluster.
.TP
.B CLUSTER 
The name of the cluster that holds the node as a member.
.TP
.B HOST
The host name of the host. This can be a real DNS host name, the IP address or
the Cmon alias name of the node depending on the configuration and the command
line options. The cluster is usually configured to use IP addresses (the Cmon
configuration file contains IP addresses) so this field usually shows IP
addresses.
.TP 
.B PORT
The IP port on which the node accepts requests. The same DNS host name or IP
address can be added multiple times to the same or to multiple clusters, but the
host:port pair must be unique. In other words the same host with the same port
can not be added to the same Cmon controller twice. Since the hostname:port pair
is unique the nodes are identified by this and every line of the node list is
representing a hostname:port node. There is one exception for this rule: the
Cmon Controller can manage multiple clusters and so be a part of more than
one clusters with the same hostname and port. 
.TP 
.B COMMENT
A short human-readable description that the Cmon Controller sets automatically
to describe the host state. A single '-' character is shown if the controller
did not set the message.
.RE

The color highlighting of the node list is controlled by the \fB\-\-color\fP
command line option.

.\"
.\"
.\"
.TP
.BR \-\^\-node\-format [ =\fIFORMATSTRING\fP "]
The string that controls the format of the printed information about the nodes.
When this command line option is used the specified information will be printed
instead of the default columns. The format string uses the '%' character to mark
variable fields and flag characters as they are specified in the standard
printf() C library functions. The '%' specifiers are ended by field name letters
to refer to various properties of the clusters.

The "%+12I" format string for example has the "+12" flag characters in it with
the standard meaning: the field will be 12 character wide and the "+" or "-"
sign will always be printed with the number. 

The properties of the message are encoded by letters. The in the "%16D" for
example the letter "D" encodes the "data directory" field, so the full path of
the data directory on the node will be substituted. 

Standard '\\' notation is also available, \\n for example encodes a new-line 
character.

The s9s-tools support the following fields:

.RS 7
.TP
.B A
The alias of the node. The alias is a secondary name that the user can assign 
to the node. Please check the "examples" section to see how an alias can be
assigned to a specific host.

.TP
.B C
The class name of the node. This is mostly for debugging purposes, but it can
also help applications classify the nodes.

.TP
.B c
The configuration file for the most important process on the node (e.g. the
configuration file of the MySQL daemon on a Galera node).

.TP
.B D
The data directory of the node. This is usually the data directory of the SQL
server.

.TP
.B d
The PID file on the node.

.TP
.B g
The log file on the node.

.TP
.B I
The numerical ID of the node.

.TP
.B i
The IP address of the node.

.TP
.B N
The name of the name. If the node has an alias that is used, otherwise the name
of the node is used. If the node is registered using the IP address the IP
address is the name.

.TP
.B M
A message, describing the node's status un human readable format.

.TP
.B m
Maintenance mode flag. If the node is in maintenance mode a letter 'M',
otherwise '-'.

.TP
.B O
The name and version of the operating system together with the codename.

.TP
.B L
The replay location. This field currently only has valid value in PostgreSQL
clusters.

.TP
.B l
The received location. This field currently only has valid value in PostgreSQL
clusters.

.TP
.B P
The port on which the most important service is awaiting for requests.

.TP
.B p
The PID (process ID) on the node that presents the service (e.g. the PID of the
MySQL daemon on a Galera node).

.TP
.B R 
The role of the node (e.g. "controller", "master", "slave" or "none").

.TP
.B r
The work "read-only" or "read-write" indicating if the server is in read only
mode or not.

.TP
.B S
The status of the host (e.g. CmonHostUnknown, CmonHostOnline, CmonHostOffLine,
CmonHostFailed, CmonHostRecovery, CmonHostShutDown).

.TP
.B s
The list of slaves of the given host in one string.

.TP
.B T
The type of the node, e.g. "controller", "galera", "postgres".

.TP
.B U
The uptime of the service on the host. Please note that this is not the uptime
of the host, it is the uptime of the most important service (e.g. the uptime of
the PostgreSQL server software).

.TP
.B V
The version string of the most important software (e.g. the version of the
PostgreSQL installed on a PostgreSQL node).


.TP
.B %
The '%' character itself.

.RE


.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
List the nodes managed by the controller:

.nf
# \fBs9s node \\
    --list \\
    --long \\
    --controller=https://localhost:9556 \\
    --color=always\fR
.fi

List a few specific nodes from one specific cluster:

.nf
# \fBs9s node \\
    --list \\
    --long \\
    --cluster-name=ft_postgresql_36945 \\
    '*168.0*' '10.10*'\fR
.fi

Installing a new Galera cluster with three nodes:

.nf
# \fBs9s cluster \\
    --create \\
    --cluster-type=galera \\
    --nodes=192.168.1.117;192.168.1.241;192.168.1.242 \\
    --vendor=percona \\
    --cluster-name=ft_galera_43788 \\
    --provider-version=5.6 \\
    --log\fR
.fi

The next example shows how to add a slave node to a cluster. Please note that
adding a new node to an existing cluster is a cluster operation.

.nf
# \fBs9s cluster \\
    --add-node \\
    --cluster-id=1 \\
    --nodes=192.168.1.117?master;192.168.1.240?slave \\
    --log \fR
.fi

The following example shows how a node in a given cluster can be restarted. When
this command executed a new job will be created to restart a node. The command
line tool will stop and show the job messages until the job is finished.

.nf
# \fBs9s node \\
    --restart \\
    --cluster-id=1 \\
    --nodes=192.168.1.117 \\
    --log\fR
.fi

Change a configuration value for a PostgreSQL server:

.nf
# \fBs9s node \\
    --change-config \\
    --nodes=192.168.1.115 \\
    --opt-name=log_line_prefix \\
    --opt-value='%m '\fR
.fi

Change the "alias" property for a host, giving it a "nickname" to be used in
lists and command line options:

.nf
# \fBs9s node \\
    --set \\
    --nodes=192.168.1.127 \\
    --properties="alias=controller"\fR
.fi


