.TH S9S-JOB 1 "August 29, 2016"

.SH NAME
s9s_job \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-job
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP is command line tool to manage and monitor... more info needed...

.SH OPTIONS

.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B \-\^\-delete
Delete the job referenced by the job ID. 

.TP
.B \-L, \-\-list
List jobs.

.TP
.B \-\-log
Print the job messages of the specified job.

.TP
.B \-\-wait
Wait for the specified job to end. While waiting a progress bar will be shown
unless the silent mode is set.

.\"
.\"
.\"
.SS General Options

.TP
.B \-\-help
Print the help message and exist.

.TP
.B \-\-debug
Print even the debug level messages.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " \fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" \fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The port is also accepted as part of the
hostname.

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.BI \-u " USERNAME" "\fR,\fP \-\^\-cmon\-user=" USERNAME
Sets the name of the Cmon user (the name of the account maintained by the Cmon
Controller) to be used to authenticate. Since most of the functionality needs
authentication this command line option should be very frequently used or set in
the configuration file. Please check the documentation of the s9s.conf(5) to see
how the Cmon User can be set using the \fBcmon_user\fP configuration variable.

.TP
.BI \-p " PASSWORD" "\fR,\fP \-\^\-password=" PASSWORD
The password for the Cmon User (whose user name is set using the 
\fB\-\^\-cmon\-user\fP command line option or using the \fBcmon_user\fP
configuration value). Providing the password is not mandatory, the user
authentication can also be done using a private/public keypair automatically.

.TP
.BI \-\^\-private\-key\-file= FILE
The path to the private key file that will be used for the authentication. The
default value for the private key is \fB~/.s9s/username.key\fP.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .
.TP

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.TP
.BI \-\^\-date\-format= FORMATSTRING
Controls what format the dates and times will be printed. Formats strings
accepted as specified in the strftime(3) man page.

.\"
.\"
.\"
.SS Job Related Options

.TP
.BR \-\^\-job\-id =\fIID\fP
The job ID of the job to handle or view.

.TP
.BR \-\^\-from= \fIDATE&TIME\fP
Controls the start time of the period that will be printed in the job list.

.TP
.BR \-\^\-limit= \fINUMBER\fP
Limits the number of jobs printed.

.TP
.BR \-\^\-offset= \fINUMBER\fP
Controls the relative index of the first item printed.

.TP
.BR \-\^\-until= \fIDATE&TIME\fP
Controls the end time of the period that will be printed in the job list.

.TP
.BR \-\^\-log\-format [ =\fIFORMATSTRING\fP "]
The string that controls the format of the printed log and job messages. The
format string uses the '%' character to mark variable fields, flag characters as
they are specified in the standard printf() C library functions and its own
field name letters to refer to the various properties of the messages. 

The "%+12I" format string for example has the "+12" flag characters in it with
the standard meaning: the field will be 12 character wide and the "+" or "-"
sign will always be printed with the number.

Standard '\\' notation is also available, \\n for example encodes a new-line 
character.

The properties of the message are encoded by letters. The in the "%-5L" for
example the letter "L" encodes the "line-number" field, so the number of the
source line that produced the message will be substituted. The program supports
the following fields:

.RS 7
.TP
.B B
The base name of the source file that produced the message. 

.TP
.B C
The creation date&time that marks the exact moment when the message was
created. The format of the date&time sustituted can be set using the 
\fB\-\^\-date\-format\fP command line option.

.TP
.B F
The name of the source file that created the message. This is similar to the
\fBB\fR fields, but instead of the base name the entire file name will be
substituted.

.TP
.B I
The ID of the message, a numerical ID that can be used as a unique identifier
for the message.

.TP
.B J
The Job ID.

.TP
.B L
The line number in the source file where the message was created. This property
is implemented mostly for debugging purposes.

.TP
.B M
The message text.

.TP
.B S 
The severity of the message in text format. This field can be "MESSAGE",
"WARNING" or "FAILURE".

.TP
.B T
The creation time of the message. This is similar to the \fBC\fR field, but
shows only hours, minutes and seconds instead of the full date and time.

.TP
.B %
The '%' character itself. 

.RE

.\"
.\"
.\"
.SH JOB LIST
Using the \fB\-\-list\fP command line option a detailed list
of jobs can be printed (the \fB\-\-long\fP option results in even more details).
Here is an example of such a list:

.nf
# \fBs9s job --list\fP
ID CID STATE    OWNER  GROUP  CREATED             RDY  TITLE
 1   0 FINISHED pipas  users  2017-04-25 14:12:31 100% Create MySQL Cluster
 2   1 FINISHED system admins 03:00:15            100% Removing Old Backups
Total: 2

.fi
The list contains the following fields:
.RS 5
.TP
.B ID
The numerical ID of the job. The \fB\-\-job-id\fP command line option can be
used to pass such ID numbers.
.TP 
.B CID
The cluster ID. Most of the jobs are related to one specific cluster so those
have a cluster ID in this field. Some of the jobs are not related to any
cluster, so they are shown with cluster ID 0.
.TP
.B STATE
The state of the job. The possible values are DEFINED, DEQUEUED, RUNNING, 
SCHEDULED, ABORTED, FINISHED and FAILED.
.TP
.B OWNER
The user name of the user who owns the job.
.TP
.B GROUP
The name of the group owner.
.TP
.B CREATED
The date and time showing when the job was created. The format of this timestamp
can be set using the \fB\-\^\-date\-format\fP command line option.
.TP
.B RDY
A progress indicator showing how many percent of the job was done. Please note
that some jobs has no estimation available and so this value remains 0% for the
entire execution time.
.TP
.B TITLE
A short, human readable description of the job.

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
The next example shows how to list the jobs of one specific cluster. It is also
possible to print the list of all the jobs for all the clusters, and for this
the \fB--cluster-id\fP option can simply be omitted.

.nf
# \fBs9s job \\
    --list \\
    --cluster-id=1 \fR
.fi

The following example shows how to list the job messages that belong to one
specific job.

.nf
# \fBs9s job \\
    --log \\
    --job-id=5\fR

Delete the job that has the job ID 41:

.nf
# \fBs9s job \\
    --delete \\
    --job-id=42\fR
