.TH S9S 1 "August 29, 2016"

.SH NAME
s9s_job \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-job
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP is command line tool to manage and monitor... more info needed...

.SH OPTIONS
General options for \fBs9s_job\fP:
.TP

.B \-\-help
Print the help message and exist.
.TP

.B \-v, \-\-verbose
Print more messages than normally.
.TP

.B \-V, \-\-version
Print version information and exit.
.TP

.BR \-c " \fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" \fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The port is also accepted as part of the
hostname.
.TP

.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.
.TP

.TP
.BI \-u " USERNAME" "\fR,\fP \-\^\-cmon\-user=" USERNAME
The name of the user that is going to be used to authenticate on the Cmon
Controller. This can also be set as the \fBcmon_user\fP configuration file 
value, but the command line option of course has precedence over the
configuration file. 

.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.
.TP

.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .
.TP

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.TP
.BI \-\^\-date\-format= FORMATSTRING
Controls what format the dates and times will be printed. Formats strings
accepted as specified in the strftime(3) man page.

.\"
.\"
.\"
.SS Job Related Options

.TP
.B \-\-wait
Wait for the specified job to end. While waiting a progress bar will be shown
unless the silent mode is set.

.TP
.B \-\-log
Print the job messages of the specified job.

.TP
.BR \-\^\-job-id =\fIID\fP
The job ID of the job to handle or view.

.TP
.BR \-\^\-job-id =\fIID\fP
The job ID of the job to handle or view.

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
The next example shows how to list the jobs of one specific cluster:

.nf
# \fBs9s job --list --cluster-id=1 \fR
.fi

