.TH S9S-TREE 1 "October 2, 2019"

.SH NAME
s9s-alarm \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-tree
.RI [OPTION]... 
.RI [PATH]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B --delete
Sets the alarm to be ignored. This will not in fact delete the alarm, but it
will make the alarm to disappear from the active alarms list, hence the name
of the option.

.TP
.B --list
List the active alarms.

