.TH S9S 1 "August 29, 2016"

.SH NAME
s9s_job \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s_job
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP is command line tool to manage and monitor... more info needed...

.SH OPTIONS
General options for \fBs9s_job\fP:
.TP

.B \-h, \-\-help
Print the help message and exist.
.TP

.B \-v, \-\-verbose
Print more messages than normally.
.TP

.B \-V, \-\-version
Print version information and exit.
.TP

.BR \-c " \fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" \fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The port is also accepted as part of the
hostname.
.TP

.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.
.TP

.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.
.TP

.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .
.TP

