.TH S9S-CLOUD-CREDENTIALS 1 "September 16, 2026"

.SH NAME
s9s-cloud-credentials \- Command-line client for the Severalnines ClusterControl server.

.SH SYNOPSIS
.B s9s-cloud-credentials
.RI [OPTION]... 
.RI [PATH]...

.SH DESCRIPTION
\fBs9s-cloud-credentials\fP is a command-line tool for ClusterControl, which can be used to 
perform CRUD operations on stored cloud credentials supported by ClusterControl.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what operation
should be performed. This "main option" should be one of the following:

.TP
.B \-\^\-list
Gets the list of created cloud credentials.

.B EXAMPLE
.nf
s9s cloud-credentials --list
ID  NAME     PROVIDER  REGION     ENDPOINT         COMMENT
2   alvaro1  aws       us-west-1                   test
3   minioc   s3        us-east-1  10.8.9.221:9000  test_minio
.fi


.TP
.B \-\^\-create
Creates a cloud credential and stores it on ClusterControl.

.B EXAMPLE
.nf
s9s cloud-credentials --create \e
    --name=alvaro1 \e
    --cloud-provider=aws \e
    --s3-region=us-west-1 \e
    --s3-access-key-id=AKIAIOSFODNN7EXAMPLE \e
    --s3-secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \e
    --comment=test
created.

s9s cloud-credentials --create \e
    --name=minioc \e
    --cloud-provider=s3 \e
    --s3-region=us-east-1 \e
    --s3-access-key-id=AKIAIOSFODNN7EXAMPLE \e
    --s3-secret-key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \e
    --endpoint=10.8.9.221:9000 \e
    --comment=test_minio
created.
.fi


.\"
.\" Arguments related to create operation
.\"
.SS Arguments related to create operation
IMPORTANT: As this command is used to store sensitive information, it is recommended to use initial ' ' to avoid storing command on history.
The create operation has some optional and mandatory arguments that must be used to create a cloud credential.
Let's differentiate them starting with the mandatory ones:

.TP
.BI \-\^\-name=CREDENTIALS_UNIQUE_NAME
Internal name of the cloud credential. It must be unique.

.TP
.BI \-\^\-cloud\-provider=CLOUD_PROVIDER
The cloud provider. The possible values are: 
  - s3: S3 compatible storage provider
  - aws: Amazon Web Services
Supported by ClusterControl but to be added on s9s cloud-credentials: azure & gcp

.TP
.BI \-\^\-s3\-region=REGION_STRING " (mandatory for aws & s3 providers)"
The string to identify region as it is identified on cloud provider.
 
.TP
.BI \-\^\-s3\-access\-key\-id=ACCESS_KEY_ID_VALUE " (mandatory for aws & s3 providers)"
The string identifying access key id as on cloud provider.


.TP
.BI \-\^\-s3\-secret\-key=SECRET_KEY_VALUE " (mandatory for aws & s3 providers)"
The string identifying the secret key as on cloud provider.

.TP
.BI \-\^\-endpoint=URL_TO_ENDPOINT " (mandatory for s3 provider)"
The string after http(s):// that identifies the endpoint to be used.

.TP
.BI \-\^\-comment=COMMENT_STRING " (optional)"
A comment to be associated with the cloud credential for better identification.

.TP
.BI \-\^\-use\-ssl [=BOOLEAN] " (optional for s3 provider)"
Whether the connection to the endpoint is made over TLS. Defaults to \fBtrue\fP.

.TP
.BI \-\^\-insecure\-ssl [=BOOLEAN] " (optional for s3 provider)"
Whether the endpoint's TLS certificate is left unverified. Needed for an endpoint
that serves a self-signed or otherwise unverifiable certificate. Defaults to
\fBfalse\fP.


.TP
.B \-\^\-delete
Deletes a cloud credential stored on ClusterControl.

.B EXAMPLE
.nf
s9s cloud-credentials --delete \e
    --credential-id=1 \e
    --cloud-provider=aws
deleted.
.fi


.\"
.\" Arguments related to delete operations
.\"
.TP
.BI \-\^\-credential\-id=CC_CREDENTIAL_ID
The credential id used on ClusterControl to identify the cloud credential as shown
by the list operation.

.TP
.BI \-\^\-cloud\-provider=CLOUD_PROVIDER
The cloud provider the credential to be deleted belongs to.