.TH S9S-USER 1 "August 29, 2016"

.SH NAME
s9s-user \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s-cluster
.RI [OPTION]...
.RI [USERNAME]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
.SS "Main Option"
The application should always be started using a main option that sets what
operation should be performed. This "main option" should be one of the
following:

.TP
.B \-L, \-\-list
List the users registered for the ClusterControl controller. 

.TP
.B \-\-whoami
Same as \fB\-\-list\fR, but only lists the current user, the user that
authenticated on the controller.

.TP
.B \-\-create
Register a new user or update an existing user on the controller and grant
access to the ClusterControl system.

.SS Generic Options

.TP
.B \-\-help
Print the help message and exist.

.TP
.B \-\-debug
Print even the debug level messages.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " [\fIPROT\fP://]\fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" [\fIPROT\fP://]\\fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The protocol and port is also accepted as
part of the hostname (e.g. --controller="https://127.0.0.1:9556").

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.B \-l, \-\-long
This option is similar to the -l option for the standard ls UNIX utility
program. If the program creates a list of objects this option will change its
format to show more details.

.TP
.B \-\-print-json
The JSON strings will be printed while communicating with the controller. This 
option is for debugging purposes.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .

.TP
.B \-\-batch
Print no messages. If the application created a job print only the job ID number
and exit. If the command prints data do not use syntax highlight, headers,
totals, only the pure table to be processed using filters.

.TP
.B \-\-no\-header
Do not print headers for tables.

.\"
.\"
.\"
.SS Options Related to Users

.TP
.BI \-\^\-cmon-user= USERNAME
Sets the name of the Cmon user (the name of the account maintained by the Cmon
Controller) to be manipulated or used to authenticate. Since most of the
functionality needs authentication this command line option should be very
frequently used or set in the configuration file. Please check the documentation
of the s9s-conf(5) to see how the Cmon User can be set.

.TP
.BI \-\^\-group= GROUPNAME
Set the name of the group. For example when a new user is created this option
can be used to control what will be the primary group of the new user.

.TP
.BI \-\^\-create-group
Not yet implemented.

.TP
.BI \-\^\-first-name= NAME
Set the first name of the user.

.TP
.BI \-\^\-last-name= NAME
Set the last name of the user.

.TP
.BI \-\^\-title= TITLE
The title prefix (e.g. Dr.) for the user.

.TP
.BI \-\^\-email-address= ADDRESS
The email address for the user.

.\"
.\"
.\"
.SH USER LIST
Using the \fB\-\-list\fP and \fB\-\-long\fP command line options a detailed list
of the users can be printed. Here is an example of such a list:

.nf
# \fBs9s user --list --long worf jadzia\fP
A ID UNAME  GNAME EMAIL           REALNAME
- 11 jadzia ds9   dax@ds9.com     Lt. Jadzia Dax
A 12 worf   ds9   warrior@ds9.com Lt. Worf
Total: 12

.fi

Please note that there are a total of 12 users defined on the system, but only
two of those are printed because we filtered the list with the command line
arguments.

The list contain the following fields:
.RS 5

.TP
.B A
Shows the authentication status. If this field shows the letter 'A' the user is
authenticated with the current connection.

.TP 
.B ID
Shows the user ID, a unique numerical ID identifying the user.

.TP 
.B UNAME
The username.

.TP
.B GNAME
The name of the primary group of the user. All user belongs to at least one
group, the primary group.

.TP
.B EMAIL
The email address of the user.

.TP
.B REALNAME
The real name of the user that consists first name, last name and some other
parts, printed here as a single string composed all the available components.

.RE

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\" 
.\" The examples. The are very helpful for people just started to use the
.\" application.
.\" 
.SH EXAMPLES
.PP
The first example will create a new user (if it is not yet created), set some
properties for the new user (like the first name and the last name) and grant
acess to the system using a public SSL key that is created (if it is not yet
created):

.nf
# \fBs9s user \\
    --create \\
    --generate-key \\
    --cmon-user=john \\
    --first-name="John" \\
    --last-name="Doe" \\
    --group=admins\fR
.fi

Here is how to get a detailed list of the users managed by the controller.

# \fBs9s user \\
    --list \\
    --long\fR
