.TH S9S.CONF 5 "October 03, 2016"
.SH NAME
s9s.conf \- configuration file for the s9s command line tool
.SH SYNOPSIS
.B ~/s9s/s9s.conf

.B /etc/s9s.conf
.SH DESCRIPTION
.TP
\fBbackup_directory\fP 
The directory where the created backup files will be placed on the target host.
If this value is not specified the cluster configuration \fBBACKUPDIR\fP is
going to be used. If the cluster has no configuration either the backup will
fail.

.TP
\fBbackup_method\fP 
Defines what software will be used to create the backup. Valid values are 
\fBauto\fP, \fBmysqldump\fP, \fBxtrabackup\fP... well, I am not sure, this is
again not properly documented. :(

.TP
\fBcontroller_host_name\fP 
The host name of the Cmon controller.

.TP
\fBcontroller_protocol\fP 
Something like "http" or "https".

.TP
\fBcontroller_port\fP 
The port where the controller is accepting requests.

.TP
\fBdefault_cluster_id\fP 
The cluster ID that will be used when no cluster ID is provided in the command
line (--cluster-id command line option).

.TP
\fBos_user\fP 
The name of the user that will be used when authenticating on the nodes with
SSH.

.TP
\fBos_key_file\fP 
The file (on the controller) that will be used as SSH key while authenticating
on the nodes with SSH.

.TP
\fBprovider_version\fP
The version of the SQL software that will be installed when no value is set by
the --provider-version command line option.

.TP
\fBcmon_user\fP
The Cmon user name used to authenticate the user on the Cmon system and identify
the owner of the objects the user creates (e.g. owner of the cluster). 

.TP
\fBvendor\fP 
Database software vendor name to be used when installing new clusters.

