.TH S9S.CONF 5 "October 03, 2016"
.SH NAME
s9s.conf \- configuration file for the s9s command line tool
.SH SYNOPSIS
.B ~/s9s/s9s.conf
.B /etc/s9s.conf
.SH DESCRIPTION
.TP
\fBcontroller_host_name\fP The host name of the Cmon controller.

.TP
\fBcontroller_port\fP The port where the controller is accepting requests.
