.TH S9S 1 "August 29, 2016"

.SH NAME
s9s \- Command line client for the Severalnines ClusterControl server.
.SH SYNOPSIS
.B s9s
.RI [COMMAND]
.RI [OPTION]...
.SH DESCRIPTION
\fBs9s\fP  is a command line tool for ClusterControl, which can be used to
deploy and operate MySQL, MariaDB, MongoDB and PostgreSQL.

.SH OPTIONS
General options for \fBs9s\fP:

.TP
.B \-h, \-\-help
Print the help message and exist.

.TP
.B \-v, \-\-verbose
Print more messages than normally.

.TP
.B \-V, \-\-version
Print version information and exit.

.TP
.BR \-c " \fIHOSTNAME\fP[:\fIPORT\fP]" "\fR,\fP \-\^\-controller=" \fIHOSTNAME\fP[:\fIPORT\fP]
The host name of the Cmon Controller. The port is also accepted as part of the
hostname.

.TP
.BI \-P " PORT" "\fR,\fP \-\^\-controller-port=" PORT
The port where the Cmon Controller is waiting for connections.

.TP
.BI \-t " STRING" "\fR,\fP \-\^\-rpc-token=" STRING
The RPC token to be used when authenticating on the Cmon Controller.

.TP
.BR \-\^\-color [ =\fIWHEN\fP "]
Turn on and off the syntax highlighting of the output. The supported values for 
.I WHEN
is
.BR never ", " always ", or " auto .

.\"
.\"
.\"
.SH ENVIRONMENT
The s9s application will read and consider the following environment variables:
.TP 5 
CMON_CONTROLLER
The host name and optionally the port number of the controller that will be
contacted. This also can be set using the \fB\-\-controller\fR command line
option.

.TP 5
CMON_CLUSTER_ID
The numerical ID of the cluster to control, same as the \fB\-\-cluster\-id\fR
command line option.

.\"
.\"
.\"
.SH EXAMPLES
List the clusters and the nodes managed by the controller:

.RS
# s9s cluster --list --controller=localhost:9555 --color=always

# s9s node --list --long --controller=localhost:9555
.RE


Get the job list for the specified cluster maintained by the specified
controller:
.RS

# s9s job --list --cluster-id=1  --controller=localhost:9555
.RE
