.TH S9S 1 "August 29, 2016"

.SH NAME
S9s \- Command line client for the Severalnines Clustercontrol server.
.SH SYNOPSIS
.B s9s
.RI COMMAND 
.RI [ OPTION ]...
.SH DESCRIPTION
\fBs9s\fP is command line tool to manage and monitor... more info needed...

.SH OPTIONS
General options \fBs9s\fP:
.TP
.B \-h, \-\-help
Print the help message and exist.
printed as integers.
.TP
.B \-v, \-\-verbose
Print more messages than normally.
.TP

