#! /bin/bash
MYNAME=$(basename $0)
MYDIR=$(dirname $0)
MYDIR=$(readlink -m "$MYDIR")
VERSION="0.0.2"
VERBOSE=""
LOGFILE=""
HOST=""
SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet"
HOST_ID=""
source $MYDIR/utilityfunctions.sh


export LC_ALL=C

# sysv-rc-conf --level 5 piphostc on
# sysv-rc-conf --level 6 piphostc off
# sysv-rc-conf --level 0 piphostc off
# sysv-rc-conf --list | grep pip
# /etc/init.d/piphostc
#


#
# Prints the software version and exits.
#
function printVersionAndExit()
{
    echo "$MYNAME Version $VERSION on $(hostname)" >&2
    exit 0
}

#
# $*: the error message
#
#
# Prints an error message to the standard error. The text will not mixed up with
# the data that is printed to the standard output.
#
function printError()
{
    local datestring=$(date "+%Y-%m-%d %H:%M:%S")

    echo -e "$MYNAME($$) $*" >&2

    if [ "$LOGFILE" ]; then
        echo -e "$datestring ERROR $MYNAME($$) $*" >>"$LOGFILE"
    fi
}

#
# $*: the message
#
# Prints all the arguments but only if the program is in the verbose mode.
#
function printVerbose()
{
    local datestring=$(date "+%Y-%m-%d %H:%M:%S")

    if [ "$VERBOSE" == "true" ]; then
        echo -e "$MYNAME($$) $*" >&2
    fi

    if [ "$LOGFILE" ]; then
        echo -e "$datestring DEBUG $MYNAME($$) $*" >>"$LOGFILE"
    fi
}

function printHelpAndExit()
{
cat <<EOF
Usage:
  $MYNAME [OPTION]... 

  $MYNAME - Monitors various system properties and reports them through MQTT.

  -h, --help           Print this help and exit.
  -v, --version        Print version information and exit.
  --verbose            Print more messages.
  --log-file=FILE      Store all the messages in the given file too.
  --id=INTEGER         Set the host ID.

EXAMPLES:

EOF
    exit 0
}

ARGS=$(\
    getopt \
        -o hvs:c:l \
        -l "help,verbose,version,log-file:,id:" \
        -- "$@")

if [ $? -ne 0 ]; then
    exit 6
fi

eval set -- "$ARGS"
while true; do
    case "$1" in
        -h|--help)
            shift
            printHelpAndExit
            ;;

        --verbose)
            shift
            VERBOSE="true"
            VERBOSE_OPTION="--verbose"
            ;;

        -v|--version)
            shift
            VERSION_OPTION="--version"
            ;;

        --log-file)
            shift
            LOGFILE=$(readlink -m "$1")
            shift
            ;;

        --id)
            shift
            HOST_ID="$1"
            shift
            ;;

        --)
            shift
            break
            ;;

        *)
            ;;
    esac
done

function mqtt_config_file()
{
    local file_name="$HOME/.pip/mqtt.conf"

    if [ ! -f "$file_name" ]; then
        printVerbose "Creating '$file_name'."

        mkdir -p "$(dirname $file_name)" 2>/dev/null
cat <<EOF >$file_name
#
# Configuration file created by $MYNAME $(date)
#
MQTT_SERVER="192.168.0.5"
MQTT_PORT=1883
MQTT_USER="pipas"
MQTT_PASSWORD="p"
EOF
    fi

    echo "$file_name"
}

#
# Prints detailed memory measurements in JSon format.
#
function get_memory_measurements()
{
    local line=$(free | grep -i '^Mem:')
    local total=$(echo "$line" | awk '{print $2}')
    local available=$(echo "$line" | awk '{print $7}')

    echo "{ \"Total\": $total, \"Available\": $available }"
}

function get_disk_throughput()
{
    local lines=$(sudo iotop -qbokn 4)
    local read_kilo
    local write_kilo

    printVerbose "lines: $lines"

    write_kilo=$(\
        echo "$lines" | grep "Actual DISK WRITE" | tail -n 1 | \
        awk '{print $10}')

    read_kilo=$(\
        echo "$lines" | grep "Actual DISK READ" | tail -n 1 | \
        awk '{print $4}')

    if [ -z "$read_kilo" ]; then
        read_kilo="null"
    fi
    
    if [ -z "$write_kilo" ]; then
        write_kilo="null"
    fi

    echo "{ \"ReadKps\": $read_kilo, \"WriteKps\": $write_kilo }"
}

function get_load()
{
    cat /proc/loadavg | awk '{print $1}'
}

#
# Prints the memory and load in JSon format.
#
function get_resources()
{
    local hostname=$(hostname)
    local load=$(get_load)
    local memory=$(get_memory_measurements)
    local nproc=$(nproc)
    local n_containers=$(get_number_of_containers)
    local throughput=$(get_disk_throughput)
    local message

    message="{\
\"hostname\":\"$hostname\", \
\"Load\":$load, \
\"NProc\": $nproc, \
\"NContainers\": $n_containers, \
\"Memory\": $memory, \
\"DiskThroughput\": $throughput}"
    echo "$message"
}

CONFIG_FILE=$(mqtt_config_file)
if [ ! -f "$CONFIG_FILE" ]; then
    printError "Config file '$CONFIG_FILE' not found."
    exit 5
else
    printVerbose "Loading config file '$CONFIG_FILE'."
    source "$CONFIG_FILE"
    printVerbose "    MQTT_SERVER=$MQTT_SERVER"
    printVerbose "      MQTT_PORT=$MQTT_PORT"
    printVerbose "      MQTT_USER=$MQTT_USER"
    printVerbose "  MQTT_PASSWORD=$MQTT_PASSWORD"
fi

#
# Sends the load of the local computer to the mqtt broker.
#
function local_resources_to_mqtt()
{
    local hostname=$(hostname)
    local topic="stat/${hostname}/resources"
    local message=$(get_resources)
    local retcode

    echo "------------------------------------"
    echo "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
    echo "    topic: $topic"
    echo "  message: $message"
    mosquitto_pub \
        -u "$MQTT_USER" \
        -P "$MQTT_PASSWORD" \
        -h "$MQTT_SERVER" \
        -p "$MQTT_PORT" \
        -t "$topic" \
        -m "$message"

    retcode=$?
    echo "  retcode: $retcode"
}

function get_disk_stats()
{
    local hostname=$(hostname)
    local line
    local total
    local used
    local available
    local percent
    local sum

    line=$(df --total | grep total)
    total=$(echo "$line" | awk '{print $2}')
    used=$(echo "$line" | awk '{print $3}')
    available=$(echo "$line" | awk '{print $4}')
    percent=$(echo "$line" | awk '{print $5}' | tr -d '%')

    sum="\"Total\": $total, \"Used\": $used, \"Free\": $available, \"Percent\": $percent"

    echo "{\"Sum\": {$sum}, \"hostname\": \"$hostname\", \"id\": $HOST_ID}"
}

#
# 
#
function disks_to_mqtt()
{
    local hostname=$(hostname)
    local topic="stat/${hostname}/disks"
    local message=$(get_disk_stats)
    local retcode

    echo "------------------------------------"
    echo "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
    echo "    topic: $topic"
    echo "  message: $message"
    mosquitto_pub \
        -u "$MQTT_USER" \
        -P "$MQTT_PASSWORD" \
        -h "$MQTT_SERVER" \
        -p "$MQTT_PORT" \
        -t "$topic" \
        -m "$message"

    retcode=$?
    echo "  retcode: $retcode"
}

# {"StatusSNS":{"Time":"1970-01-16T05:49:55","ENERGY":{"Total":35.640,"Yesterday":0.000,"Today":35.640,"Power":0,"Factor":0.00,"Voltage":218,"Current":0.000}}}"

function get_power()
{
    local pdu_name=$1
    local power=$(pip-pdu-control --power $pdu_name)
    local current=$(pip-pdu-control --current $pdu_name)
    local topic="stat/$pdu_name/STATUS10"
    local message

    message="{\"StatusSNS\":{\"ENERGY\":{\"Power\":$power,\"Current\":$current}}}"
    
    echo "------------------------------------"
    echo "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
    echo "    topic: $topic"
    echo "  message: $message"

    mosquitto_pub \
        -u "$MQTT_USER" \
        -P "$MQTT_PASSWORD" \
        -h "$MQTT_SERVER" \
        -p "$MQTT_PORT" \
        -t "$topic" \
        -m "$message"

    retcode=$?
    echo "  retcode: $retcode"
}

#
# 
#
function ping_server()
{
    local hostname=$1
    local topic="stat/${hostname}/state"
    local message=$(pip-server-control --ping --print-json $hostname)
    local retcode

    echo "------------------------------------"
    echo "     mqtt: mqtt://$MQTT_SERVER:$MQTT_PORT"
    echo "    topic: $topic"
    echo "  message: $message"
    mosquitto_pub \
        -u "$MQTT_USER" \
        -P "$MQTT_PASSWORD" \
        -h "$MQTT_SERVER" \
        -p "$MQTT_PORT" \
        -t "$topic" \
        -m "$message"

    retcode=$?
    echo "  retcode: $retcode"
}

function emit_rc_file()
{
    cat <<EOF
#! /bin/bash
# chkconfig: 2345 20 80

### BEGIN INIT INFO
# Provides:          pipscripts
# Required-Start:    
# Required-Stop:     
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Remote monitoring
# Description:       Remote monitoring and control with pipscripts.
### END INIT INFO


LOCKFILE="/var/lock/subsys/pipscripts"

function start()
{
    # Touch our lock file so that stopping will work correctly
    touch \${LOCKFILE}

    sudo -H -u pipas bash -c 'pip-host-control --verbose --status "Started."'
}

function stop()
{
        # Remove our lock file
        rm \${LOCKFILE}

        # Run that command that we wanted to run
        sudo -H -u pipas bash -c 'pip-host-control --verbose --status "Shut down."'
}

case "\$1" in
    start) start;;
    stop) stop;;
    *)
        echo $"Usage: \$0 {start|stop}"
        exit 1
esac

exit 0
EOF


}

function run_checks()
{
    local rc_file="/etc/init.d/pipscripts"
    local level
    
    for f in /etc/rc5.d/S20piphostc /etc/rc3.d/S20piphostc \
        /etc/rc2.d/S20piphostc /etc/rc4.d/S20piphostc \
        /etc/rc1.d/S20piphostc /etc/init.d/piphostc \
        /etc/rc0.d/K80piphostc /etc/rc6.d/K80piphostc; 
    do
        if [ -f $f ]; then
            sudo rm $f
        fi
    done

    if [ ! -f "$rc_file" ]; then
        emit_rc_file | sudo tee "$rc_file" >/dev/null
        sudo chmod +x "$rc_file"

        sudo apt -y --force-yes install sysv-rc-conf
        for level in 5 4 3 2 1; do
            sudo sysv-rc-conf --level $level pipscripts on
        done

        sudo sysv-rc-conf --level 0 pipscripts off
        sudo sysv-rc-conf --level 6 pipscripts off 
    fi
    
}


#
# mpt-status 
# ioc0 vol_id 0 type IME, 8 phy, 543 GB, state OPTIMAL, flags ENABLED
# ioc0 phy 7 scsi_id 8 HP       DG146BABCF       HPD5, 136 GB, state ONLINE, flags NONE
# ioc0 phy 6 scsi_id 1 HP       DG146BABCF       HPD5, 136 GB, state ONLINE, flags NONE
#

if [ -z "$HOST_ID" ]; then
    case "$(hostname)" in
        t7500)
            HOST_ID=0
            ;;

        core1)
            HOST_ID=1
            ;;

        storage01)
            HOST_ID=2
            ;;

        laptop01)
            HOST_ID=3
            ;;

        *)
            HOST_ID=10
            ;;
    esac
fi

if [ $VERSION_OPTION ]; then
    printVersionAndExit
else
    run_checks

    hostname=$(hostname)
    if [ "$hostname" == "t7500" -o "$hostname" == "core1" ]; then
        for h in core1 core2 core3 t7500 storage01 laptop01 \
            www dns1 dns2 mqtt; 
        do
            ping_server $h
        done
    fi

    if [ "$(hostname)" == "t7500" ]; then
        get_power pdu01
        get_power pdu02
    fi

    local_resources_to_mqtt
    disks_to_mqtt
    sleep 15
    
    local_resources_to_mqtt
    sleep 15
    
    local_resources_to_mqtt
    sleep 15
    
    local_resources_to_mqtt
    sleep 15
fi
