#! /bin/bash

#clusterssh host01 host02 host03 host04 host05 host06 host07 host08
clusterssh \
    blade01 \
    blade02 \
    blade03 \
    blade04 \
    blade05 \
    blade06 \
    blade07 \
    blade08 \
    blade09 \
    blade10

