#! /bin/bash

export MYNAME=$(basename $0)
export MYDIR=$(dirname $0)
export MYDIR=$(readlink -m "$MYDIR")
export VERSION="0.0.2"

OPTION_MONITORED_HOST=""
OPTION_PROTECTED=""
OPTION_CHANNEL_GREEN=""
OPTION_CHANNEL_RED=""
OPTION_CHANNEL_BLUE=""
OPTION_FLASH=""

LINE1_OLD=""
LINE2_OLD=""
LINE3_OLD=""
LINE4_OLD=""

LINE1_NEW=""
LINE2_NEW=""
LINE3_NEW=""
LINE4_NEW=""


if [ -f "$MYDIR/utilityfunctions.sh" ]; then
    source $MYDIR/utilityfunctions.sh
else
    echo "File '$MYDIR/utilityfunctions.sh' was not found." >&2
    exit 5
fi

function printHelpAndExit()
{
    cat <<EOF 
Usage:
  $MYNAME [OPTION]... HOST_NAME

  $MYNAME - Security monitor script.

  -h, --help           Print this help and exit.
  -v, --version        Print version information and exit.
  --verbose            Print more messages.

  --flash
  --protected          Monitor a protected resource.
  --led1
  --led2
EOF
  exit 0
}

ARGS=$(\
    getopt \
        -o hvs:c:l \
        -l "help,version,verbose,flash,protected,led1,led2" \
        -- "$@")

if [ $? -ne 0 ]; then
    exit 6
fi

eval set -- "$ARGS"
while true; do
    case "$1" in
        -h|--help)
            shift
            printHelpAndExit
            ;;

        --verbose)
            shift
            VERBOSE="true"
            ;;

        -v|--version)
            shift
            printVersionAndExit
            ;;

        --protected)
            shift
            OPTION_PROTECTED="true"
            ;;

        --flash)
            shift
            OPTION_FLASH="true"
            ;;

        --led1)
            shift
            OPTION_PORT="LED1"
            ;;

        --led2)
            shift
            OPTION_PORT="LED2"
            ;;

        --)
            shift
            break
            ;;

        *)
            break
            ;;
    esac
done

#
# Checking the system.
#
if [ -z $(which "gpio") ]; then
    printError "The gpio program was not found."
    exit 6
fi

#
# Checking command line options.
#
if [ -n "$1" ]; then
    OPTION_MONITORED_HOST="$1"
fi

if [ "$OPTION_PORT" == "LED1" ]; then
    OPTION_CHANNEL_GREEN=14
    OPTION_CHANNEL_RED=15
    OPTION_CHANNEL_BLUE=18
elif [ "$OPTION_PORT" == "LED2" ]; then
    OPTION_CHANNEL_GREEN=17
    OPTION_CHANNEL_RED=27
    OPTION_CHANNEL_BLUE=22
fi

function initialize_gpio()
{
    #
    # Setting the GPIO ports to output mode.
    #
    for id in $OPTION_CHANNEL_GREEN $OPTION_CHANNEL_RED $OPTION_CHANNEL_BLUE; do
        gpio -g mode $id out
    done
}

function set_color_to()
{
    while [ -n "$1" ]; do
        case "$1" in 
            --dark)
                gpio -g write $OPTION_CHANNEL_GREEN 0
                gpio -g write $OPTION_CHANNEL_RED 0
                gpio -g write $OPTION_CHANNEL_BLUE 0
                shift
                ;;

            --red)
                gpio -g write $OPTION_CHANNEL_GREEN 0
                gpio -g write $OPTION_CHANNEL_RED 1
                gpio -g write $OPTION_CHANNEL_BLUE 0

                shift
                ;;

            --green)
                gpio -g write $OPTION_CHANNEL_GREEN 1
                gpio -g write $OPTION_CHANNEL_RED 0
                gpio -g write $OPTION_CHANNEL_BLUE 0
                shift
                ;;
            
            --yellow)
                gpio -g write $OPTION_CHANNEL_GREEN 1
                gpio -g write $OPTION_CHANNEL_RED 1
                gpio -g write $OPTION_CHANNEL_BLUE 0
                shift
                ;;
            
            --blue)
                gpio -g write $OPTION_CHANNEL_GREEN 0
                gpio -g write $OPTION_CHANNEL_RED 0
                gpio -g write $OPTION_CHANNEL_BLUE 1
                shift
                ;;
            
            --white)
                gpio -g write $OPTION_CHANNEL_GREEN 1
                gpio -g write $OPTION_CHANNEL_RED 1
                gpio -g write $OPTION_CHANNEL_BLUE 1
                shift
                ;;

            --short-sleep)
                sleep 0.5 
                shift 
                ;;

            --)
                break
                ;;

            *)
                break
                ;;
        esac
    done
}

function atexit_handler()
{
    set_color_to --dark
}

function led_test()
{
    set_color_to --red
    sleep 0.10

    set_color_to --green
    sleep 0.10

    set_color_to --blue
    sleep 0.10
 
    set_color_to --dark
}

function line_update()
{
    local lines
    
    if [ "$LINE1_NEW" != "$LINE1_OLD" -o \
        "$LINE2_NEW" != "$LINE2_OLD" -o \
        "$LINE3_NEW" != "$LINE3_OLD" -o \
        "$LINE4_NEW" != "$LINE4_OLD" ]; \
    then
        lines=$(pip-server-control --only-report --print-report --list)
        LINE2_NEW="--------------------"
        LINE3_NEW=$(echo "$lines" | head -n 1 | tr -d '\n')
        LINE4_NEW=$(echo "$lines" | tail -n 1 | tr -d '\n')

        sudo python lcdout.py \
            "$LINE1_NEW" "$LINE2_NEW" "$LINE3_NEW" "$LINE4_NEW"

        clear 
        echo "$LINE1_NEW"
        echo "$LINE2_NEW"
        echo "$LINE3_NEW"
        echo "$LINE4_NEW"

        LINE1_OLD="$LINE1_NEW"
        LINE2_OLD="$LINE2_NEW"
        LINE3_OLD="$LINE3_NEW"
        LINE4_OLD="$LINE4_NEW"
    fi

}

trap atexit_handler EXIT

led_test

#
#
#
count=0
while true; do
    if [ "$ok" == "true" ]; then
        set_color_to --green
        sleep 5
    elif [ "$ok" == "false" -a -n "$OPTION_PROTECTED" ]; then
        for i in $(seq 0 5); do
            set_color_to --red --short-sleep --dark --short-sleep
        done
    elif [ "$ok" == "false" ]; then
        set_color_to --dark
        sleep 5
    fi

    if [ -n "$OPTION_FLASH" ]; then
        set_color_to --white
    fi

    ok="true"
    timeout 0.3 ping -c 1 -i 1 "$OPTION_MONITORED_HOST" \
        2>/dev/null >/dev/null
    if [ $? -ne 0 ]; then 
        ok="false"
    fi


    let count+=1
    LINE1_NEW="$(date +"%V  %F %H:%M")"
    #LINE1_NEW="$(date +"%F %H:%M:%S")"
    #LINE2_NEW="$count"
    line_update
done

