#! /bin/bash
MYNAME=$(basename $0)
MYDIR=$(dirname $0)
MYDIR=$(readlink -m "$MYDIR")
VERSION="0.0.1"
VERBOSE=""
LOGFILE=""
SERVER=""

#
# Prints the software version and exits.
#
function printVersionAndExit()
{
    echo "$MYNAME Version $VERSION on $(hostname)" >&2
}

#
# $*: the error message
#
#
# Prints an error message to the standard error. The text will not mixed up with
# the data that is printed to the standard output.
#
function printError()
{
    local datestring=$(date "+%Y-%m-%d %H:%M:%S")

    echo -e "$MYNAME($$) $*" >&2

    if [ "$LOGFILE" ]; then
        echo -e "$datestring ERROR $MYNAME($$) $*" >>"$LOGFILE"
    fi
}

#
# $*: the message
#
# Prints all the arguments but only if the program is in the verbose mode.
#
function printVerbose()
{
    local datestring=$(date "+%Y-%m-%d %H:%M:%S")

    if [ "$VERBOSE" == "true" ]; then
        echo -e "$MYNAME($$) $*" >&2
    fi

    if [ "$LOGFILE" ]; then
        echo -e "$datestring DEBUG $MYNAME($$) $*" >>"$LOGFILE"
    fi
}

function printHelpAndExit()
{
cat <<EOF
Usage:
  $MYNAME [OPTION]... [CONTAINER_NAME]...

  $MYNAME - Creates and starts containers.

 -h, --help           Print this help and exit.
 -v, --version        Print version information and exit.
 --verbose            Print more messages.
 --log-file=FILE      Store all the messages in the given file too.
 --server=SERVER      Create the container on remote server.

EOF
    exit 0
}

ARGS=$(\
    getopt \
        -o hvs:c:l \
        -l "help,verbose,version,log-file:,server:" \
        -- "$@")

if [ $? -ne 0 ]; then
    exit 6
fi

eval set -- "$ARGS"
while true; do
    case "$1" in
        -h|--help)
            shift
            printHelpAndExit
            ;;

        --verbose)
            shift
            VERBOSE="true"
            VERBOSE_OPTION="--verbose"
            ;;

        -v|--version)
            shift
            VERSION_OPTION="--version"
            ;;

        --log-file)
            shift
            LOGFILE=$(readlink -m "$1")
            shift
            ;;

        --server)
            shift
            SERVER="$1"
            shift
            ;;

        --)
            shift
            break
            ;;

        *)
            ;;
    esac
done

function emit_config_file()
{
    local file_name="$HOME/.pip/say.conf"

    printVerbose "Creating '$file_name'."

    mkdir -p "$(dirname $file_name)" 2>/dev/null
    cat <<EOF >$file_name
#
#
#
#MQTT_SERVER="192.168.1.104"
#MQTT_TOPIC="tts/say"
EOF
}

#
# Checking command line arguments.
#
EXTRA_OPTIONS=$*

#
# The configuration.
#
if [ ! -f "$HOME/.pip/say.conf" ]; then
    emit_config_file
else
    source "$HOME/.pip/say.conf"
fi

if [ "$MQTT_SERVER" -a "$MQTT_TOPIC" ]; then
    MOSQUITTO=$(which mosquitto_pub)
    if [ "$MOSQUITTO" ]; then
        printVerbose "Sending with MQTT server '$MQTT_SERVER'."
        mosquitto_pub -t "$MQTT_TOPIC" -h "$MQTT_SERVER" -m "$EXTRA_OPTIONS"
        exit 0
    else
        printError "The mosquitto_pub program was not found."
    fi
fi

#
# Doing the job.
#
if [ -z "$SERVER" ]; then
    if [ "$VERSION_OPTION" ]; then
        printVersionAndExit
        exit 0
    else
        if [ "$(which festival)" ]; then
            echo $EXTRA_OPTIONS | festival --tts
        fi
    fi
else
    #
    # We received the --server option and so we run the script on a remote
    # server.
    #
    printVerbose "Executing on server '$SERVER'."
    ssh $SERVER -- \
        sudo $MYNAME \
            $VERSION_OPTION \
            $VERBOSE_OPTION \
            $EXTRA_OPTIONS
fi

#
# I just want to notice the message before the caller continues to do things.
#
# sleep 3
