#! /bin/bash

MYNAME=$(basename $0)
MYDIR=$(dirname $0)
MYDIR=$(readlink -m "$MYDIR")
PATH=${MYDIR}:${PATH}
VERSION="0.0.1"

OPTION_CONTINUOUS=""

START_TIME=$(date)
LAST_TEST_STARTED="-"
LAST_TEST_NAME="-"
LAST_HOST_NAME="-"
LAST_USER_NAME="-"
SUM_STARTED_TESTS=0

if [ -f "$MYDIR/load_config.sh" ]; then
    source $MYDIR/load_config.sh
else
    echo "File $MYDIR/load_config.sh was not found." >&2
    exit 5
fi


#source "./utilityfunctions.sh"
#[ -f "./htmlfunctions.sh" ] && source "./htmlfunctions.sh"

#
# Prints the help text and exits.
#
function printHelpAndExit()
{
cat <<EOF
Usage:
  $MYNAME [OPTION]... 

  $MYNAME - Runs tests as they appear in the file-system.

  -h, --help         Print this help and exit.
  -v, --version      Print version information and exit.
  --verbose          Print more messages.
  --log-file=FILE    Store all the messages in the given file too.
  --continuous       Continue watching if no schedules found.

EOF
    exit 0
}

ARGS=$(\
    getopt \
        -o hv \
        -l "help,verbose,version,log-file:,continuous" \
        -- "$@")

if [ $? -ne 0 ]; then
    exit 6
fi

eval set -- "$ARGS"
while true; do
    case "$1" in
        -h|--help)
            shift
            printHelpAndExit
            ;;

        --verbose)
            shift
            VERBOSE_OPTION="--verbose"
            ;;

        -v|--version)
            shift
            printVersionAndExit
            ;;

        --continuous)
            shift
            OPTION_CONTINUOUS="true"
            ;;

        --)
            shift
            break
            ;;

        *)
            break
            ;;
    esac
done

#
# Waits until it finds an idle server, then starts the given test on it.
#
function start_test()
{
    local config_file="$1"
    local idle_server=""
    local testname=""
    local state=""
    local user=""
    local project=""
    local option_s9s=""
    local retcode
    local counter

    echo "Loading '$config_file'..."
    source "$config_file"
    local gitcommit="$githash"

    # 
    # Getting the list of available servers.
    #
    echo "Getting idle test servers"

    let counter=0
    echo "pip-server-control --list --idle"
    idle_server=$(pip-server-control --list --idle | head -n 1)
    if [ -z "$user" ]; then
        user="$USER"
    fi

    if [ "$idle_server" == "" ]; then
        echo "No idle test server available"
        return 6
    fi

    logbasename="$PROJECT_TEST_REPORT_DIR/${testname}-${gitbranch}-${gitcommit}"
    pipcmontestlog="${logbasename}.pip-cmon-test.log"

    LAST_USER_NAME="$user"

    echo " --------------------------------------"
    echo "      idle_server: $idle_server"
    echo "         testname: $testname"
    echo "            state: $state"
    echo "             user: $user"
    echo "          project: $project"
    echo "       git branch: $gitbranch"
    echo "       git commit: $gitcommit"
    echo "pip-cmon-test.log: $pipcmontestlog"
    echo ""

    if [ "$project" == "s9s-tools" ]; then
        option_s9s="--s9s"
    fi

    LAST_TEST_STARTED=$(date)
    LAST_TEST_NAME="$testname"
    LAST_HOST_NAME="$idle_server"

    let SUM_STARTED_TESTS+=1

    echo "pip-cmon-test "\
        "$VERBOSE_OPTION "\
        "$option_s9s "\
        "--test=$testname "\
        "--user=$user "\
        "--git-branch=$gitbranch"\
        "--git-commit=$gitcommit"

    #nohup ?
    pip-cmon-test \
        $VERBOSE_OPTION \
        $option_s9s \
        --test="$testname" \
        --user="$user" \
        --git-branch="$gitbranch" \
        --git-commit="$gitcommit" > ${pipcmontestlog} 2> ${pipcmontestlog}

    mv "$PROJECT_LOGDIR/pip-cmon-test.log" "${logbasename}.slog"

    rm -f "$config_file"

    #clear
    echo ""
    printf "        Start time: %s\n" "$START_TIME"
    printf "      Current time: %s\n" "$(date)"
    printf " Last test started: %s\n" "$LAST_TEST_STARTED"
    printf "\n"
    printf "    Last test name: %s\n" "$LAST_TEST_NAME"
    printf "         Last user: %s\n" "$LAST_USER_NAME"
    printf "    Last host name: %s\n" "$LAST_HOST_NAME"
    printf "           Started: %'d test(s)\n" "$SUM_STARTED_TESTS"
    printf "\n\n\n"
}

#
# Lists the schedule files in reverse timestamp order (oldest files first).
#
function schedule_files()
{
    local root_dir="$PROJECT_DATA_ROOT"

    if [ -z "$root_dir" ]; then
        root_dir="/var/lib/test-ui"
    fi

    if [ ! -d "$root_dir" ]; then
        printError "The project root dir '$root_dir' does not exist."
        return 1
    fi

    ls -tr $root_dir/scheduled-tests/*.conf 2>/dev/null
}

function pull_local_testorigin_source()
{
    if [ "${PROJECT_AUTO_PULL_TESTORIGIN}" == "true" ]; then

        echo "Pulling in ${idle_server}:${PROJECT_CC_TESTORIGIN_DIR}"

        pushd "${PROJECT_CC_TESTORIGIN_DIR}"
        git reset --hard HEAD >/dev/null 2>/dev/null
        git pull >/dev/null 2>/dev/null
        popd

        echo "Pulling in ${idle_server}:${PROJECT_S9S_TESTORIGIN_DIR}"

        pushd "${PROJECT_S9S_TESTORIGIN_DIR}"
        git reset --hard HEAD >/dev/null 2>/dev/null
        git pull >/dev/null 2>/dev/null
        popd
    fi
}

#
# The main function that does some polling by checking the scheduled tests and
# returns once in every round.
#
function process_scheduled_tests()
{
    local config_file
    local config_files=$(schedule_files)

    if [ -z "$config_files" ]; then
        #echo "No tests scheduled."
        return 0
    fi

    pull_local_testorigin_source

    for config_file in $(schedule_files); do
        echo "*** config_file: $config_file"
        if [ ! -f "$config_file" ]; then
            continue
        elif [ ! -x "$config_file" ]; then
            # Files that are not executable are being created and not yet 
            # ready.
            continue
        fi

        start_test "$config_file"
    done
}

if [ "$OPTION_CONTINUOUS" ]; then
    while true; do
        process_scheduled_tests
        sleep 10
    done
else 
    process_scheduled_tests
fi

