#! /bin/bash

MYNAME=$(basename $0)
MYDIR=$(dirname $0)
MYDIR=$(readlink -m "$MYDIR")
VERSION="0.0.4"
VERBOSE=""
LOGFILE=""
TARGET_HOST=""

#
# Prints an error message to the standard error. The text will not mixed up with
# the data that is printed to the standard output.
#
function printError()
{
    local datestring=$(date "+%Y-%m-%d %H:%M:%S")

    echo -e "$MYNAME($$) $*" >&2

    if [ "$LOGFILE" ]; then
        echo -e "$datestring ERROR $MYNAME($$) $*" >>"$LOGFILE"
    fi
}

TARGET_HOST="$1"

if [ -z "$TARGET_HOST" ]; then
    printError "The first argument should be the target host."
    exit 6
fi

scp $MYDIR/pip-* $TARGET_HOST:
ssh $TARGET_HOST -- sudo mv pip-* /usr/bin
