#! /bin/bash
MYNAME=$(basename $0)
MYDIR=$(dirname $0)
MYDIR=$(readlink -m "$MYDIR")
VERSION="0.0.16"
VERBOSE=""
LOGFILE=""

source $MYDIR/utilityfunctions.sh

#
# Prints the help text and exits.
#
function printHelpAndExit()
{
cat <<EOF
Usage:
  $MYNAME [OPTION]...

  $MYNAME - Installs a development environment to the local server. 

  -h, --help         Print this help and exit.
  -v, --version      Print version information and exit.
  --verbose          Print more messages.
  --log-file=FILE    Store all the messages in the given file too.
  
  --all              Check everything, install everything.
  --install-mongodb  Checks and installs the mongodb driver and mongo-c.
  --install-mysql    Installs the mysql server with root password.
  --update-packages  Updates packages of the server.

EOF
    exit 0
}

ARGS=$(\
    getopt \
        -o hv \
        -l "help,verbose,version,log-file:,all,\
install-mongodb,install-mysql,update-packages" \
        -- "$@")

if [ $? -ne 0 ]; then
    exit 6
fi

eval set -- "$ARGS"
while true; do
    case "$1" in
        -h|--help)
            shift
            printHelpAndExit
            ;;

        --verbose)
            shift
            VERBOSE="true"
            ;;

        -v|--version)
            shift
            printVersionAndExit
            ;;

        --log-file)
            shift
            LOGFILE=$(readlink -m "$1")
            shift
            ;;

        --all)
            shift
            OPTION_ALL="true"
            ;;

        --install-mongodb)
            shift
            OPTION_INSTALL_MONGODB="true"
            ;;

        --install-mysql)
            shift
            OPTION_INSTALL_MYSQL="true"
            ;;

        --update-packages)
            shift
            OPTION_INSTALL_PACKAGES="true"
            ;;

        --)
            shift
            break
            ;;

        *)
            ;;
    esac
done

function install_package() 
{
    local package
    local retcode=0
    local tempfile=$(mktemp)

    package="$1"

    printf "%-32s" "${package}"
    if dpkg -l | grep " $1 " > /dev/null 2>&1; then
        echo "[INSTALLED]"
    else
        echo "[INSTALLING]"
        sudo apt-get -y --force-yes install "$package" >>$tempfile 2>>$tempfile
        retcode=$?

        if [ "$retcode" != "0" ]; then
            cat "$tempfile"
        fi
    fi

    rm -f "$tempfile"
    return $retcode
}

function check_install_libssh_ppa()
{
    echo -ne "Checking for libssh 0.7.x ... "
    if dpkg -l | grep "libssh-4.*0.7" > /dev/null 2>&1; then
        echo "OK (0.7)" # installed
    elif dpkg -l | grep "libssh-4.*0.8" > /dev/null 2>&1; then
        echo "OK (0.8)" # installed
    else
        echo "Not installed, installing"
        sudo apt-get -y --force-yes install software-properties-common $1
        sudo apt-add-repository -y -u ppa:kedazo/libssh-0.7.x
        sudo apt-get -y -q update
        sudo apt-get -y --force-yes install libssh-dev libssh-4 libssh-dbg
    fi
}

function install_mysql_server()
{
    #
    # Installing mysql-server with a root password.
    #
    echo "mysql-server-5.5 mysql-server/root_password password p" |\
        sudo debconf-set-selections
    echo "mysql-server-5.5 mysql-server/root_password_again password p" |\
        sudo debconf-set-selections

    install_package mysql-server
}

function install_packages()
{
    pip-host-control --status="Installing packages..."
    install_package lxc1
    install_package jq
    install_package tree
    install_package iotop
    install_package wget
    install_package git
    install_package autoconf
    install_package make
    install_package g++
    install_package flex
    install_package bison

    #install_package vagrant
    #install_package virtualbox
    install_mysql_server
}

#
# Install dependencies
#
function install_dependencies()
{
    pip-host-control --status="Installing dependencies..."

    install_package git
    install_package wget
    install_package xz-utils
    install_package make
    install_package g++
    install_package flex
    install_package bison
    install_package rpm
    install_package dpkg-dev
    install_package cmake
    install_package libssl-dev
    check_install_libssh_ppa

    # for mongodb
    install_package libboost-dev

    #check_install_dep libboost-all-dev
    install_package libboost-filesystem-dev
    install_package libboost-program-options-dev
    install_package libboost-regex-dev
    install_package libboost-system-dev
    install_package libboost-test-dev
    install_package libboost-thread-dev
    install_package scons
}


#
# Downloading clustercontrol source
#
function pull_clustercontrol_source()
{
    pushd "$HOME" >/dev/null 2>/dev/null 

    pip-host-control --status="Installing clustercontrol..."
    if [ -d "clustercontrol-enterprise" ]; then
        cd clustercontrol-enterprise
        git pull
    else
        git clone git@github.com:severalnines/clustercontrol-enterprise.git
        cd "clustercontrol-enterprise"
        
        docs/ubuntu_compile.sh
        RETCODE=$?
        echo "+++ RETCODE: $RETCODE"

        if ! grep 'mysql-cluster-gpl-7.2' ~/.bashrc; then
            # FIXME: This should actually find the directory.
            echo 'export PATH=/opt/mysql-cluster-gpl-7.2.28-linux2.6-x86_64/bin:$PATH' \
            >> ~/.bashrc
            echo "Modified ~.bashrc"
        fi

    fi

    popd >/dev/null 2>/dev/null
}

function compile_clustercontrol()
{
    local source_dir="$HOME/clustercontrol-enterprise"

    pip-host-control --status="Compiling clustercontrol..."
    
    if [ ! -d "$source_dir" ]; then
        echo "Directory '$source_dir' is not found."
        return 1
    fi

    pushd "$source_dir"
    ./autogen.sh
    make -j20
    popd 

    pushd "$source_dir/tests"
    ./autogen.sh
    make -j20
    popd 
}

function pull_s9s_source()
{
    pushd "$HOME" >/dev/null 2>/dev/null 

    pip-host-control --status="Installing s9s..."
    if [ -d "s9s-tools" ]; then
        cd s9s-tools
        git pull
    else
        git clone git@github.com:severalnines/s9s-tools.git
        #cd "s9s-tools"
    fi

    popd >/dev/null 2>/dev/null
}

function compile_s9s()
{
    local source_dir="$HOME/s9s-tools"

    pip-host-control --status="Compiling s9s..."
    
    if [ ! -d "$source_dir" ]; then
        echo "Directory '$source_dir' is not found."
        return 1
    fi

    pushd "$source_dir"
    ./autogen.sh
    make -j20
    popd 
}


function install_mongodb()
{
    tmp_dir="/var/tmp/pip_install_dev_mongodb_$$"

    if grep -q 'MONGO_SASL 1' /opt/mongo/include/mongo/config.h; then
        echo "The mongodb-driver (with sasl) is already installed."
        return 0
    fi

    #
    #
    #
    mkdir -p "$tmp_dir"
    if [ ! -d "$tmp_dir" ]; then
        echo "Failed to create directory '$tmp_dir'."
        return 1
    fi

    echo "Entering directory '$tmp_dir'..."
    pushd "$tmp_dir" >/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Failed to enter directory"
        return 1
    fi

    #
    #
    #
    echo "Downloading the SASL library for MongoDb."
    wget https://www.cyrusimap.org/releases/cyrus-sasl-2.1.26.tar.gz 
    if [ $? -ne 0 ]; then
        echo "Failed to download source"
        return 1
    fi
    
    echo "* installing the SASL library for MongoDb."
    tar -xzpf cyrus-sasl-2.1.26.tar.gz || exit $?

    pushd cyrus-sasl-2.1.26
    ./configure --enable-scram --disable-gssapi --enable-static=yes --prefix=/opt/cyrus-sasl || exit $?
    make -j3 || exit $?
    sudo make -j3 install || exit $?
    popd

    if ! [ -f legacy-1.1.3.tar.gz ]; then
        echo "* downloading mongodb-driver."
        wget --no-check-certificate https://github.com/mongodb/mongo-cxx-driver/archive/legacy-1.1.3.tar.gz || exit $?
    fi

    echo "* compiling mongodb-driver."
    tar -xzpvf legacy-1.1.3.tar.gz || exit $?

    pushd mongo-cxx-driver-legacy-1.1.3/
    sudo mv -f /opt/mongo /opt/mongo.bak || true
    sudo mkdir -p /opt/mongo;
    sudo chown -R ${USER} /opt/mongo || exit $?;
    #scons --prefix=/opt/mongo --ssl=on --dynamic-boost=off --opt=on install
    CXXFLAGS='-std=c++0x' scons --prefix=/opt/mongo --c++11=off CXXFLAGS='-std=c++0x' --ssl=on --dynamic-boost=off --use-sasl-client=on --disable-warnings-as-errors=on --opt=on --cpppath=/opt/cyrus-sasl/include/ --libpath=/opt/cyrus-sasl/lib/ install;# || exit $? # FIXME CheckCXX(), c++ compiler test fails 
    popd
    
    popd
}

function install_mongoc()
{
    local tmp_dir="/var/tmp/pip_install_dev_mongoc_$$"

    if [ -f /opt/mongo-c/include/libmongoc-1.0/mongoc.h ]; then
        echo "The mongo-c is already installed."
        return 0
    fi

    #
    #
    #
    mkdir -p "$tmp_dir"
    if [ ! -d "$tmp_dir" ]; then
        echo "Failed to create directory '$tmp_dir'."
        return 1
    fi

    echo "Entering directory '$tmp_dir'..."
    pushd "$tmp_dir" >/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Failed to enter directory"
        return 1
    fi

    if [ ! -f mongo-c-driver-1.12.0.tar.gz ]; then
        wget 'https://github.com/mongodb/mongo-c-driver/releases/download/1.12.0/mongo-c-driver-1.12.0.tar.gz' || exit $?
    fi

    echo "* installing the new MongoC driver"
    tar -xzpf mongo-c-driver-1.12.0.tar.gz || exit $?
    
    pushd mongo-c-driver-1.12.0
    cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/mongo-c -DMONGOC_ENABLE_ICU=OFF
    make -j3 || exit $?
    sudo make -j3 install
    popd

    #
    #
    #
    popd
    rm -rvf "$tmp_dir"
}

function update_packages()
{
    local tmp

    sudo apt update
    sudo apt -y --force-yes upgrade
    sudo apt -y --force-yes autoremove

    tmp=$(which purge-old-kernels)
    if [ -z "$tmp" ]; then
        sudo apt -y --force-yes install byobu
    fi

    sudo purge-old-kernels
}

if [ -n "$OPTION_INSTALL_MYSQL" ]; then
    install_mysql_server
    exit $?
fi

if [ -n "$OPTION_INSTALL_PACKAGES" ]; then
    update_packages
fi

if [ -n "$OPTION_ALL" ]; then
    install_packages
    [ $? -ne 0 ] && exit 1
    
    install_dependencies
    [ $? -ne 0 ] && exit 1
    
    install_mongodb
    [ $? -ne 0 ] && exit 1
    
    install_mongoc
    [ $? -ne 0 ] && exit 1

    pull_clustercontrol_source
    compile_clustercontrol 

    pull_s9s_source
    compile_s9s
elif [ -n "$OPTION_INSTALL_MONGODB" ]; then
    install_mongodb
    [ $? -ne 0 ] && exit 1
    
    install_mongoc
    [ $? -ne 0 ] && exit 1
else
    echo "Nothing to do, no command line option is provided with tasks."
fi

pip-host-control --status="Idle"

