.TH PIP-PDU-CONTROL 1 "August 11, 2019"
.SH NAME
pip-pdu-control - Command line tool to control power distribution units.
.SH SYNOPSIS
.B pip-pdu-control
.RI [OPTION]...
.RI [DEVICE]...

.SH OPTIONS
.SS "Main Option"
The main options control what the program will do. The main options are one of
the following:

.TP
.B --discover
Contact the device and creates a new configuration file if the devices replies
and there is no configuration file for it.

.B EXAMPLE
.nf
pip-pdu-control --discover 192.168.2.32
.fi

.TP
.B --list
List the devices and their poperties.

.TP
.B --list-measurements

.TP
.B --list-outlets
List the outlets of the devices and their state.

.B EXAMPLE
.nf
pip-pdu-control --list-outlets pdu01 pdu02
.fi
